### ISSUE TITLE
TypeError: application.register is not a function

### ISSUE THREAD

**Issue by miharekar** [hotwired/stimulus-rails#72]
After upgrading from 0.4.1 to 0.4.2 I get a bunch of these in the console and, obviously, Stimulus is not working.

<img width="1272" alt="CleanShot 2021-09-06 at 11 02 49" src="https://user-images.githubusercontent.com/986645/132190649-ef0e096c-c035-4190-860d-5dc79cde3a6d.png">

The browser points me to `then` line in this function:
```
function registerControllerFromPath(path, under, application) {
  const name = path
    .replace(`${under}/`, "")
    .replace("_controller", "")
    .replace(/\//g, "--")
    .replace(/_/g, "-")

  import(path)
    .then(module => application.register(name, module.default))
    .catch(error => console.log(`Failed to register controller: ${name} (${path})`, error))
};
```

Probably an issue in stimulus itself…
